### PR TITLE
Simplified ctr_object_type

### PR DESCRIPTION
**Pull request by janus**
Just removed the sentinel marks '\0' and re-organized using switch instead of IF statement.

### CODE REVIEW

**Comment by takano32** [comment]
I'm interested in your this commit.
What is your editor  for writing programming language C code?

**Comment by takano32** [comment]
sorry, not this but these. :)

**Comment by gabordemooij** [comment]
I could cherry-pick the commits individually...

**Comment by gabordemooij** [comment]
Cherry picked 9390588, rest is a bit harder.... can someone help?

**Comment by janus** [comment]
I use codeblock IDE .... I started using it while on window box ... And I have continued using it while on linux box. Please let me know the one you are using, maybe I would migrate to it.

**Comment by janus** [comment]
@gabordemooij 

You have picked well .... Thanks .. Leave the rest ... I hope not to have this kind of issue. I am learning git and other stuff at same time. I hope to pass this phase soon. Once again thanks.

**Comment by gabordemooij** [comment]
Dont worry, I recommend to archive your branch and create a new one based on the master, so you start clean. Then, before you commit, check your changes with:

     git diff

Try to commit as concise as possible, an ideal commit contains only one feature or fix and is quite small and coherent. Also try to spot red blocks, they mark unused space, these are to be removed.

Modern IDEs are quite powerful but they also happen to do a lot of stuff you dont want. Personally I stick with Geany. http://www.geany.org/

**Comment by janus** [comment]
Thanks ... I have done that..... I have a cook IDE and just update my cloned repo.

**Comment by takano32** [comment]
Thank you, @janus and @gabordemooij . :)
I've never used [Code::Blocks](http://www.codeblocks.org/) and [Geany](http://www.geany.org/) before, and I'll check these softwares.
I always use VIM recently.

Thanks!

**Comment by takano32** [comment]
@janus BTW, I PRed yesterday resolved conflicts. If you merge the PR this PR will be able to merged with GitHub Web interface. https://github.com/janus/citrine/pull/1

@gabordemooij If you prefer I help you in Git repository management, please add me Collaborator. Then I'll help your management of this repository. # Collaborator can control git repository as well as Creator.

### The way to add someone to collaborator:

#### click your repository settings

screen shot 2016-02-08 at 19 41 03

#### click `Collaborators` menu in sidebar

screen shot 2016-02-08 at 19 41 21

#### and search account you want to add to Collaborator

screen shot 2016-02-08 at 19 42 03

#### at last, click `Add collaborator`

screen shot 2016-02-08 at 19 42 14

Thank you.

**Comment by gabordemooij** [comment]
Thanx, added you as collab.

**Comment by takano32** [comment]
Thanks. :+1:  :hamster:

**Pull request closed without merging**
