### PR TITLE
Problem: Freeing string when no longer needed

### PR DESCRIPTION
**Pull request by janus**
Worked on string functions so that heap created strings are freed after they are no more needed.

### CODE REVIEW

**Comment by gabordemooij** [comment]
Can you please send a pull request without the space contaminations? This makes it very hard to keep track of changes.

**Comment by janus** [comment]
Please I am new to git .. and don't really know the issue you just raised. Could you help me but pointing to the issue.

**Comment by gabordemooij** [comment]
Please allow me some time to review, works with tests now, looks awesome

**Comment by gabordemooij** [comment]
Take a look at:

https://github.com/janus/citrine/commit/fea3c0ffad123cd289645fd0ea080ae56fe7ba3c

As you see this is not just your change, it's also a lot of altered space, this makes it difficult for us to track the changes, please present your changes as a single commit containing only the change as described in the pull request.

For the rest, I love your work, looking forward to your 'clean' commit of this stuff.

**Comment by gabordemooij** [comment]
I really like your changes, can you please send a pull request containing only your changes and not the white space changes? Already expressed my thanks for your contribs on twitter:
https://twitter.com/gabordemooij/status/695912108471541760

**Pull request closed without merging**
