### PR TITLE
Global UZ Update

### PR DESCRIPTION
**Pull request by Temurumaru**
Hello dear Gabor de Mooij!
My name's Tulenov Temur.
UZ part of Citrine is ready for 90%
90% Due to the fact that there may be my inattention or conflicts in the **dictionary.h** which at this time I identify them.
I'm still identifying bugs due to edits, but I haven't found them yet. Checked and compiled everything on Fedora 38 Linux x86_64. Everything works fine.
List of edits:
**dictionary.h** - Untranslated parts, incorrect quotes and often mixed were found.
**msg.h** - Untranslated parts and quotes, and 2 more terms that I could not translate.
**example1.ctr** - Corrected to work with edits.
**example2.ctr** - Corrected to work with edits.
**example3.ctr** - Corrected to work with edits.

### CODE REVIEW

**Comment by gabordemooij** [comment]
Thanks Temur, I will look into this pull request as soon as possible. Very happy to update the Citrine/UZ edition!

**Comment by Temurumaru** [comment]
I saw an error in the tests right now I will fill in its correction

**Review by takano32 — APPROVED** [review]

**Comment by Temurumaru** [comment]
Now there should be no problems with the tests :)

**Comment by Temurumaru** [comment]
Hello, I don't understand what to do to fix this
image

**Comment by gabordemooij** [comment]
Looking into this...

**Comment by Temurumaru** [comment]
image
Hello, yes, we don't really say "Ro'yhat yangi". By the way, I was able to fix it and another question I had an error is because of the "runneruz" file there it is generated incorrectly, I could not find the source of this.

**Comment by gabordemooij** [comment]
No worries, we have these challenges with all languages, even my own language. I will look into this issue. I am very happy and thankful for your contributions so far! Much appreciated!

**Comment by gabordemooij** [comment]
I ran your version today, as soon as I changed applied the change I mentioned earlier, it worked.

`#define CTR_DICT_CODEGEN_MAP_NEW                 "(Ro'yxat yangi) "
`

The CODEGEN-lines are for code that Citrine generates when outputting a list (like print_r in PHP and __repr__ in Python).

We can add a supplement for this later, so you can add a little library in Citrine that does something like:

`Yangi Ro'yxat `

Then Yangi is an object that receives a Ro'yxat object and sends the message yangi to it.
In essence, this will then convert Yangi Ro'yxat to Ro'yxat yangi.

However, even if it does not match pure natural language this is not necessarily that bad. Even in English you say "new Object" instead of "Object new", but both are readable. So, while you can add supplements to make the code look like natural language, this is not always necessary. It is still a programming language after all, it may look a bit odd. It''s already better than writing everything in English and using archaic symbols like $%<>*!.

**Comment by gabordemooij** [comment]
Here is my pull request with the change, it works as you can see.

https://github.com/gabordemooij/citrine/pull/102

**Pull request merged**
