### PR TITLE
Fix compilation on FreeBSD

### PR DESCRIPTION
**Pull request by DennisCGc**
This pull request makes sure Citrine is able to compile cleanly on FreeBSD and also fixes a test (test0156).

### CODE REVIEW

**Comment by gabordemooij** [comment]
Hi Thanks Dennis, I will check this out soon. I just released 0.6 but I will incorporate most of the changes in 0.6.1

**Comment by DennisCGc** [comment]
Sure, no problem. Do you want me to fix the conflicts as well?

**Comment by gabordemooij** [comment]
sure if you have the time and motivation, be my guest!

**Comment by gabordemooij** [comment]
btw I am really happy that Citrine now compiles on FreeBSD as well !

**Comment by DennisCGc** [comment]
I don't know whether you received a notification or not, but I've fixed the conflicts a few days ago. :-)

**Pull request merged**
